export const ROUTES = Object.freeze({
  LOGIN: "/login",
  REGISTER: "/register",
  VERIFY_EMAIL: "/verify-email",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  OAUTH_CALLBACK: "/oauth/callback",
  UNAUTHORIZED: "/unauthorized",
  UPGRADE_REQUIRED: "/upgrade-required",
  DASHBOARD: "/",
  MONITORS: "/monitors",
  INSIGHTS: "/insights",
  BILLING: "/billing",
  ADMIN_USERS: "/admin/users",
});
